baseURL = 'https://www.piotrbelina.com/'
languageCode = 'en-us'
title = 'Piotr Belina'
theme = 'PaperMod'
googleAnalytics = 'G-GGFFCFCRMB'

enableRobotsTXT = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 10

[languages.pl]
languageName = "Polski"
weight = 2
[languages.pl.params]
languageAltTitle = "Polski"
#title = "PaperModL2"


[[languages.pl.menu.main]]
name = "O mnie"
url = "o-mnie/"
weight = 1

[[languages.pl.menu.main]]
name = "Tagi"
url = "tags/"
weight = 10

[[languages.pl.menu.main]]
name = "Archiwum"
url = "archiwum/"
weight = 5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  hideFooter = false

  [params.homeInfoParams]
  enabled = true
  Title = "Piotr Belina"
  imageUrl = "https://media-exp1.licdn.com/dms/image/C5103AQF3cVmOK4HykA/profile-displayphoto-shrink_200_200/0/1516463912609?e=1634169600&v=beta&t=T7NJAK3W49WGMgsgX_00BwmSmX7fkrPjIkp9U9DiPCs"
  Content = """
Welcome to my blog.
- I live in Gdańsk, Poland
- I am a Software Engineer & Site Reliability Engineer
- I am specialising in Go, OpentTelemety, Kubernetes and AWS
"""

  [[params.profileMode.buttons]]
    name = "Blog"
    url = "blog"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/piotrbelina"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/piotrbelina"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/piotrbelina"

  [params.assets]
  disableHLJS = true

#  [params.defaultCommentSystems]
#    remark42 = true
#  [params.commentSystems.remark42]
#    url = "http://localhost:8080"
#    site = "piotrbelina.com"

#[params.analytics.google]
#SiteVerificationTag = ""


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "prod"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://www.piotrbelina.com?region=eu-central-1"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
